### ISSUE TITLE
Trying to give training hints

### ISSUE THREAD

**Issue by hammertoe** [lcswillems/rl-starter-files#32]
Hi Lucas, this is not an issue, but more hoping you might have a moment to share some insight. Firstly, thanks for the great package. One of the few RL frameworks that support Dict Spaces! 

I am using your torch-rl and this package as a basis of something I'm playing with. The environment give spares rewards, and hence can take a long time to train. I have the benefit of having some known data to train on and so can know in advance what a 'good' move is. Hence I have extended my environment to supply an extra observation space called `hint`. I have then modified the end of the `forward` method in `model.py` to have

```
        x = self.actor(embedding)

        # XX                                                                                                                                                            
        if self.hints:
            x.zero_()
            indexes = obs.hint.type(torch.long).view(-1,1)
            x.scatter_(1, indexes, 1)
            dist = Categorical(x)
        ###                                                                                                                                                             
        else:
            dist = Categorical(logits=F.log_softmax(x, dim=1))

        x = self.critic(embedding)
        value = x.squeeze(1)

        return dist, value, memory
```

My theory was that if I can manually set the output of the actor to be a 'good' state that it would backpropogate it and learn quicker. A sort of hybrid between RL and supervised learning.

Sure enough, when I run it, the rewards go right up from the start, as the agent is always making 'good' moves, and hence gets high rewards. But... it would appear the network is not actually learning this. If I disable the hints and continue training, then it appears the training so far has learned nothing at all, and it makes very obvious bad moves.

So my question is this... does my theory make sense? Do you think I should be able to get my 'hints' to be propagated back into the network to learn? Or am I missing something fundamental here. I'm pretty new to pytorch, having mainly used tensorflow and keras in the past.

**Comment by lcswillems** [comment]
Hi @hammertoe ,

Sorry for the late answer. Very interesting question.

I would say it should help but that what you describe makes also sense, because when you stop giving hints, it will act badly where you were giving hints before and then go on states it is not used to see and becomes completely lost.

An idea: stopping progressively showing hints? I.e. introducing a probability p (that decreases over training or decreases when mean return increases) to receive a hint when a hint is available.

Another way to exploit these hints would be to do supervised learning and reinforcement learning at the same time: you do a step of reinforcement learning, then train by supervision the network on the states encountered with a hint available, then a step of reinforcement learning...

**Comment by lcswillems** [comment]
Hi @hammertoe ,

I am closing as it was more a question than an issue.
