### ISSUE TITLE
Recurrent is always True

### ISSUE THREAD

**Issue by manuel-delverme** [lcswillems/rl-starter-files#61]
Even with memory = 1, the recurrent flag is always set

**Comment by lcswillems** [comment]
As I don't understand the issue, I am closing for now. But if you can provide more information about the issue (e.g. the command that runs incorrectly and what you would expect), I will reopen

**Comment by ajberlier** [comment]
I found this issue as well. In model.py the ACModel inherits torch_ac.RecurrentACModel `class ACModel(nn.Module, torch_ac.RecurrentACModel):`. Because of this, recurrent is always set True as defined below:

```
class ACModel:
    recurrent = False

    @abstractmethod
    def __init__(self, obs_space, action_space):
        pass

    @abstractmethod
    def forward(self, obs):
        pass

class RecurrentACModel(ACModel):
    recurrent = True

    @abstractmethod
    def forward(self, obs, memory):
        pass

    @property
    @abstractmethod
    def memory_size(self):
        pass
```

Update: Looking at it further, I think that `args.mem = args.recurrence > 1` propagates all the way through to manage this. Is that correct?
